// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBycdp3ADoW2Cfop0bNpJDrWoaNCHDzOXA',
    appId: '1:795793420859:web:411abe653585d818ee621e',
    messagingSenderId: '795793420859',
    projectId: 'food-app-4bc85',
    authDomain: 'food-app-4bc85.firebaseapp.com',
    storageBucket: 'food-app-4bc85.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXztB_aaCoYz-ZxNiT68EF4Bhvwja9ww',
    appId: '1:795793420859:android:adb1e29bf05f3171ee621e',
    messagingSenderId: '795793420859',
    projectId: 'food-app-4bc85',
    storageBucket: 'food-app-4bc85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASKCOzgs20kjb3hCeKJMLJLAuqCBSBi44',
    appId: '1:795793420859:ios:71088546baa17902ee621e',
    messagingSenderId: '795793420859',
    projectId: 'food-app-4bc85',
    storageBucket: 'food-app-4bc85.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASKCOzgs20kjb3hCeKJMLJLAuqCBSBi44',
    appId: '1:795793420859:ios:71088546baa17902ee621e',
    messagingSenderId: '795793420859',
    projectId: 'food-app-4bc85',
    storageBucket: 'food-app-4bc85.firebasestorage.app',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBycdp3ADoW2Cfop0bNpJDrWoaNCHDzOXA',
    appId: '1:795793420859:web:383ae2bd23e537faee621e',
    messagingSenderId: '795793420859',
    projectId: 'food-app-4bc85',
    authDomain: 'food-app-4bc85.firebaseapp.com',
    storageBucket: 'food-app-4bc85.firebasestorage.app',
  );
}
